// Generated by CoffeeScript 1.8.0
(function() {
  var Card, RoundButton, addButton, character_data, charactersTable, charactersTableCard, detailsWindow, generateView, mainWindow;

  Titanium.UI.setBackgroundColor('#EEE');

  RoundButton = require('addButtonClass').AddButton;

  Card = require('cardClass').Card;

  mainWindow = Ti.UI.createWindow({
    title: 'Characters',
    navTintColor: '#FFEA00',
    backgroundColor: '#EEE'
  });

  mainWindow.addEventListener("open", function() {
    var actionBar;
    if (!mainWindow.activity) {
      Ti.API.error("Can't access action bar on a lightweight window.");
    } else {
      actionBar = mainWindow.activity.actionBar;
    }
    if (actionBar) {
      return actionBar.logo = 'images/plus.png';
    }
  });

  addButton = new RoundButton({
    right: '26dp',
    bottom: '26dp',
    size: '60dp'
  });

  charactersTable = Ti.UI.createTableView();

  charactersTableCard = new Card({
    top: 0,
    left: 0
  });

  charactersTableCard.add(charactersTable);

  mainWindow.add(charactersTableCard.create());

  mainWindow.add(addButton.create());

  generateView = require('mainViewController').generateView;

  character_data = require('tempdata').characters;

  detailsWindow = require('detailsWindowView').detailsWindow;

  charactersTable.addEventListener('click', function(e) {
    return detailsWindow(e.source.details);
  });

  generateView(character_data, charactersTable);

  mainWindow.open();

}).call(this);
