// Generated by CoffeeScript 1.8.0
(function() {
  var Card;

  Card = (function() {
    function Card(card) {
      this.main = Ti.UI.createView({
        width: '100%',
        height: Ti.UI.SIZE,
        layout: 'vertical'
      });
      this.wrapper = Ti.UI.createView({
        backgroundColor: '#fafafa',
        width: '100%',
        height: Ti.UI.SIZE
      });
      this.content = Ti.UI.createView({
        width: '100%',
        height: Ti.UI.SIZE,
        top: '20dp',
        bottom: '20dp',
        layout: 'vertical'
      });
      this.dropshadow = Ti.UI.createView({
        width: '100%',
        height: '3dp',
        opacity: 0.26,
        backgroundGradient: {
          type: 'linear',
          startPoint: {
            x: '0%',
            y: '0%'
          },
          endPoint: {
            x: '0%',
            y: '100%'
          },
          colors: [
            {
              color: '#000',
              offset: 0.0
            }, {
              color: '#eee',
              offset: 0.5
            }
          ]
        }
      });
      this.elements = [];
      this.add = function(element) {
        return this.elements.push(element);
      };
      this.create = function() {
        var element, _i, _len, _ref;
        _ref = this.elements;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          element = _ref[_i];
          this.content.add(element);
        }
        this.wrapper.add(this.content);
        this.main.add(this.wrapper);
        this.main.add(this.dropshadow);
        return this.main;
      };
    }

    return Card;

  })();

  exports.Card = Card;

}).call(this);
