// Generated by CoffeeScript 1.8.0
(function() {
  exports.vyragosa_loot = function(feed) {
    var text;
    text = '';
    if (feed.length === 0) {
      text = 'Has not looted Vyragosa recently.';
    } else if (feed.length === 1) {
      text = 'Has recently looted Vyragosa 1 time';
    } else {
      text = 'Has recently looted Vyragosa ' + feed.length + ' times';
    }
    return text;
  };

  exports.feed = function(feed) {
    var characterFeed, characterFeedRow, characterFeedVyragosaKill, characterFeedVyragosaTimestamp, divider, item, _i, _len;
    characterFeed = Ti.UI.createView({
      backgroundColor: '#fafafa',
      width: '100%',
      height: Ti.UI.SIZE,
      top: '10dp',
      layout: 'vertical'
    });
    for (_i = 0, _len = feed.length; _i < _len; _i++) {
      item = feed[_i];
      characterFeedRow = Ti.UI.createView({
        height: '80dp',
        backgroundColor: '#FAFAFA'
      });
      characterFeedVyragosaKill = Ti.UI.createLabel({
        text: 'Vyragosa looted',
        font: {
          fontSize: '16sp'
        },
        height: 'auto',
        left: '20dp',
        top: '20dp',
        color: '#000',
        touchEnabled: false
      });
      characterFeedVyragosaTimestamp = Ti.UI.createLabel({
        text: item + ' at 11:59PM EST',
        font: {
          fontSize: '12sp'
        },
        height: 'auto',
        left: '20dp',
        bottom: '20dp',
        color: '#757575',
        touchEnabled: false
      });
      divider = Ti.UI.createView({
        height: '2dp',
        width: '100%',
        backgroundColor: '#eee',
        left: 0,
        bottom: 0
      });
      characterFeedRow.add(characterFeedVyragosaKill);
      characterFeedRow.add(characterFeedVyragosaTimestamp);
      characterFeedRow.add(divider);
      characterFeed.add(characterFeedRow);
    }
    return characterFeed;
  };

}).call(this);
