// Generated by CoffeeScript 1.8.0
(function() {
  exports.generateView = function(characters, table) {
    var charName, charServer, character, character_rows, divider, emptyLabel, row, thumbnail, _i, _len;
    character_rows = [];
    if (characters.length > 0) {
      for (_i = 0, _len = characters.length; _i < _len; _i++) {
        character = characters[_i];
        row = Ti.UI.createTableViewRow({
          height: '80dp',
          backgroundColor: '#FAFAFA',
          details: character
        });
        charName = Ti.UI.createLabel({
          text: character.name,
          font: {
            fontSize: '16sp'
          },
          height: 'auto',
          left: '80dp',
          top: '20dp',
          color: '#000',
          touchEnabled: false
        });
        charServer = Ti.UI.createLabel({
          text: character.realm,
          font: {
            fontSize: '16sp'
          },
          height: 'auto',
          left: '80dp',
          bottom: '20dp',
          color: '#757575',
          touchEnabled: false
        });
        thumbnail = Ti.UI.createImageView({
          height: '40dp',
          width: '40dp',
          backgroundColor: '#ccc',
          borderRadius: '20dp',
          right: '20dp',
          top: '20dp'
        });
        if (character.thumbnail) {
          thumbnail.setImage(character.thumbnail);
        }
        divider = Ti.UI.createView({
          height: '2dp',
          width: '100%',
          backgroundColor: '#eee',
          left: 0,
          bottom: 0
        });
        if (characters.indexOf(character) !== (characters.length - 1)) {
          divider = Ti.UI.createView({
            height: '2dp',
            width: '100%',
            backgroundColor: '#eee',
            left: 0,
            bottom: 0
          });
          row.add(divider);
        }
        row.add(charName);
        row.add(charServer);
        row.add(thumbnail);
        character_rows.push(row);
      }
    } else {
      row = Ti.UI.createTableViewRow({
        height: '300dp',
        backgroundColor: '#EEE'
      });
      emptyLabel = Ti.UI.createLabel({
        text: 'No character data.\nAdd some to start collecting TLPD data!',
        font: {
          fontSize: '16dp',
          fontWeight: 'bold'
        },
        color: '#9E9E9E',
        textAlign: Titanium.UI.TEXT_ALIGNMENT_CENTER
      });
      row.add(emptyLabel);
      character_rows.push(row);
    }
    return table.setData(character_rows);
  };

}).call(this);
