// Generated by CoffeeScript 1.8.0
(function() {
  exports.characters = [
    {
      name: 'Ramaniscence',
      realm: 'Illidan',
      region: 'us',
      thumbnail: 'http://us.battle.net/static-render/us/illidan/63/20492351-avatar.jpg',
      feed: ['123456', '789012', '345678']
    }, {
      name: 'Fireswift',
      realm: 'Illidan',
      region: 'us',
      thumbnail: 'http://us.battle.net/static-render/us/illidan/83/33578579-avatar.jpg',
      feed: ['123456']
    }, {
      name: 'Lockoflove',
      realm: 'Illidan',
      region: 'us',
      thumbnail: 'http://us.battle.net/static-render/us/illidan/208/21741776-avatar.jpg',
      feed: []
    }
  ];

}).call(this);
